"""Generates frontend/src/types/generated.ts from the backend's Pydantic/SQLModel
models — PRD §9: "generate the frontend TypeScript types from the Pydantic/
SQLModel models so the two sides cannot drift."

Hand-rolled JSON-schema -> TS converter (via `model_json_schema()`), so this is
a single Python invocation with no Node-side dependency. Re-run with
`make gen-types` after changing any model in app/models/. Do not hand-edit the
output file.
"""

import sys
from pathlib import Path
from typing import Any

BACKEND_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND_ROOT))

from app.models.attempt import Attempt, AttemptCreate, AttemptRead, TelemetryCore  # noqa: E402
from app.models.badge import BadgeStatus  # noqa: E402
from app.models.event import Event  # noqa: E402
from app.models.game import GameMetadata, Level, Variant  # noqa: E402
from app.models.item import Item  # noqa: E402
from app.models.piece import (  # noqa: E402
    Illustration,
    IllustrationCreate,
    IllustrationGenerateRequest,
    Piece,
    PieceCreate,
    PieceUpdate,
    RemixVersion,
    RemixVersionCreate,
    RevisionPass,
    RevisionPassCreate,
    TurnLine,
    TurnLineCreate,
)
from app.models.profile import Profile, ProfileCreate, ProfileUpdate, SkillState  # noqa: E402
from app.models.rating import Rating, RatingCreate  # noqa: E402
from app.models.session import PlaySession  # noqa: E402
from app.models.skill import Skill  # noqa: E402
from app.models.stats import ProfileStats  # noqa: E402
from app.models.verification import Verification, VerificationCreate  # noqa: E402

# The exported surface: every model the frontend contract touches.
MODELS = [
    Profile,
    ProfileCreate,
    ProfileUpdate,
    SkillState,
    Skill,
    GameMetadata,
    Level,
    Variant,
    Item,
    TelemetryCore,
    AttemptCreate,
    Attempt,
    AttemptRead,
    Event,
    PlaySession,
    Verification,
    VerificationCreate,
    Rating,
    RatingCreate,
    BadgeStatus,
    ProfileStats,
    PieceCreate,
    PieceUpdate,
    Piece,
    IllustrationCreate,
    IllustrationGenerateRequest,
    Illustration,
    RevisionPassCreate,
    RevisionPass,
    RemixVersionCreate,
    RemixVersion,
    TurnLineCreate,
    TurnLine,
]

OUTPUT_PATH = BACKEND_ROOT.parent / "frontend" / "src" / "types" / "generated.ts"

_PRIMITIVE_MAP = {"string": "string", "integer": "number", "number": "number", "boolean": "boolean"}


def _ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]

    if "anyOf" in schema:
        parts = [_ts_type(sub) for sub in schema["anyOf"]]
        return " | ".join(dict.fromkeys(parts))  # de-duplicate, preserve order

    schema_type = schema.get("type")

    if schema_type == "array":
        return f"{_ts_type(schema.get('items', {}))}[]"

    if schema_type == "object":
        if "properties" in schema:
            return _render_fields(schema)
        return "Record<string, any>"

    if schema_type == "null":
        return "null"

    return _PRIMITIVE_MAP.get(schema_type, "any")


def _render_fields(schema: dict[str, Any]) -> str:
    required = set(schema.get("required", []))
    lines = []
    for name, sub in schema.get("properties", {}).items():
        optional = "" if name in required else "?"
        lines.append(f"  {name}{optional}: {_ts_type(sub)};")
    return "{\n" + "\n".join(lines) + "\n}"


def _render_enum(name: str, schema: dict[str, Any]) -> str:
    values = " | ".join(f'"{value}"' for value in schema["enum"])
    return f"export type {name} = {values};\n"


def _render_interface(name: str, schema: dict[str, Any]) -> str:
    return f"export interface {name} {_render_fields(schema)}\n"


def generate() -> str:
    chunks = [
        "// AUTO-GENERATED by backend/scripts/generate_ts_types.py — do not hand-edit.",
        "// Regenerate with `make gen-types` after changing any model in backend/app/models/.",
        "",
    ]
    emitted: set[str] = set()

    for model in MODELS:
        schema = model.model_json_schema()

        for def_name, def_schema in schema.get("$defs", {}).items():
            if def_name in emitted:
                continue
            emitted.add(def_name)
            if "enum" in def_schema:
                chunks.append(_render_enum(def_name, def_schema))
            else:
                chunks.append(_render_interface(def_name, def_schema))

        if model.__name__ in emitted:
            continue
        emitted.add(model.__name__)
        if "enum" in schema:
            chunks.append(_render_enum(model.__name__, schema))
        else:
            chunks.append(_render_interface(model.__name__, schema))

    return "\n".join(chunks) + "\n"


def main() -> None:
    output = generate()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(output)
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
