// AUTO-GENERATED by backend/scripts/generate_ts_types.py — do not hand-edit.
// Regenerate with `make gen-types` after changing any model in backend/app/models/.

export interface Profile {
  id?: number | null;
  name: string;
  avatar: string;
  birth_year: number;
  reading_support?: boolean;
  created_at?: string;
}

export interface SkillState {
  id?: number | null;
  profile_id: number;
  skill_id: string;
  mastery_level?: number;
}

export interface Skill {
  id: string;
  title: string;
  description?: string | null;
}

export interface GameMetadata {
  id: string;
  title: string;
  tagline: string;
  skill_ids: string[];
  min_age: number;
  max_age: number;
  icon: string;
  max_level: number;
}

export interface Level {
  id?: number | null;
  profile_id: number;
  game_id: string;
  value?: number;
  updated_at?: string;
}

export interface Variant {
  id?: number | null;
  game_id: string;
  key: string;
  title: string;
  config?: Record<string, any>;
  is_active?: boolean;
}

export interface Item {
  item_id: string;
  game_id: string;
  variant_id?: string | null;
  level: number;
  payload: Record<string, any>;
}

export interface TelemetryCore {
  correct?: boolean | null;
  score?: number | null;
  hints_used: number;
  time_ms: number;
}

export interface AttemptCreate {
  item_id: string;
  profile_id: number;
  game_id: string;
  variant_id?: string | null;
  session_id?: string | null;
  telemetry: TelemetryCore;
  details?: Record<string, any>;
}

export interface Attempt {
  id?: number | null;
  item_id: string;
  profile_id: number;
  game_id: string;
  variant_id?: string | null;
  session_id?: string | null;
  level: number;
  correct?: boolean | null;
  score?: number | null;
  hints_used: number;
  time_ms: number;
  details?: Record<string, any>;
  created_at?: string;
}

export interface AttemptRead {
  id: number;
  correct: boolean | null;
  score: number | null;
  hints_used: number;
  time_ms: number;
  event_id: string;
  hint_offered: boolean;
}

export type EventType = "session_start" | "session_complete" | "session_abandoned" | "item_shown" | "attempt" | "hint_used" | "difficulty_changed" | "replay_chosen" | "game_switched" | "quick_quit" | "rating_given" | "verification_completed" | "piece_created" | "piece_revised" | "piece_deleted" | "illustration_added" | "badge_awarded";

export interface Event {
  event_id?: string;
  timestamp?: string;
  profile_id: number;
  game_id: string;
  variant_id?: string | null;
  session_id?: string | null;
  event_type: EventType;
  payload?: Record<string, any>;
}

export interface PlaySession {
  id?: string;
  profile_id: number;
  game_id: string;
  variant_id?: string | null;
  started_at?: string;
  ended_at?: string | null;
}

export interface Verification {
  id?: number | null;
  attempt_id: number;
  correct: boolean;
  verified_at?: string;
  verified_by?: string;
}

export interface VerificationCreate {
  attempt_id: number;
  correct: boolean;
  verified_by?: string;
}

export type RatingScale = "faces" | "stars_1_5";

export interface Rating {
  id?: number | null;
  profile_id: number;
  game_id: string;
  variant_id?: string | null;
  scale: RatingScale;
  value: number;
  created_at?: string;
}

export interface RatingCreate {
  profile_id: number;
  game_id: string;
  variant_id?: string | null;
  scale: RatingScale;
  value: number;
}

export interface BadgeStatus {
  key: string;
  name: string;
  description: string;
  art_url: string;
  earned: boolean;
  awarded_at?: string | null;
}

export interface ProfileStats {
  total_stars: number;
  day_streak: number;
  minutes_this_week: number;
  most_played_game?: string | null;
  avg_rating?: number | null;
  last_session_at?: string | null;
  progress_delta_pct?: number | null;
}

export interface PieceCreate {
  profile_id: number;
  game_id: string;
  session_id?: string | null;
  title?: string | null;
  body?: string;
  constraints?: string[];
  art_style?: string | null;
}

export interface PieceUpdate {
  title?: string | null;
  body?: string | null;
}

export interface Piece {
  id?: string;
  profile_id: number;
  game_id: string;
  session_id?: string | null;
  title?: string | null;
  body?: string;
  word_count?: number;
  constraints?: string[];
  art_style?: string | null;
  created_at?: string;
  revised_at?: string | null;
}

export interface IllustrationCreate {
  prompt_excerpt: string;
  image_url: string;
  order?: number;
  is_hero?: boolean;
}

export interface IllustrationGenerateRequest {
  prompt_excerpt: string;
  order?: number;
  is_hero?: boolean;
}

export interface Illustration {
  id?: number | null;
  piece_id: string;
  prompt_excerpt: string;
  image_url: string;
  order?: number;
  is_hero?: boolean;
  created_at?: string;
}

export interface RevisionPassCreate {
  questions_asked?: string[];
  changed?: boolean;
}

export interface RevisionPass {
  id?: number | null;
  piece_id: string;
  questions_asked?: string[];
  changed?: boolean;
  completed_at?: string;
}

export interface RemixVersionCreate {
  style_key: string;
  body: string;
  is_favourite?: boolean;
}

export interface RemixVersion {
  id?: number | null;
  piece_id: string;
  style_key: string;
  body: string;
  is_favourite?: boolean;
  created_at?: string;
}

export type TurnAuthor = "kid" | "ai";

export interface TurnLineCreate {
  author: TurnAuthor;
  text: string;
  order?: number;
}

export interface TurnLine {
  id?: number | null;
  piece_id: string;
  author: TurnAuthor;
  text: string;
  order?: number;
  created_at?: string;
}

