/**
 * Pathfinder: No Way Back — curated levels.
 *
 * Easy levels are hand-authored (see each one's comment) and solver-
 * verified. Medium, Hard, and Legendary are procedurally generated by
 * `pathfinderGenerator.ts` — a simulated-annealing search over which grid
 * cells hold a dot, using `assessDifficulty`'s score as the fitness
 * function — because hand-guessing "hard-looking" shapes didn't reliably
 * produce boards that were actually hard to solve. Several early
 * hand-authored Hard/Legendary levels (a big rectangle with one obstacle;
 * a 180-dot "Colossus") turned out to have a near-1 backtrack ratio: a
 * systematic sweep solves them with essentially no trial and error, no
 * matter how large they look. The generator instead searches directly for
 * boards with a high backtrack ratio (see pathfinderDifficulty.ts), so
 * "hard" here means "a naive search has to backtrack a lot to find a
 * path" — which is what actually makes a puzzle hard for a person too.
 * Legendary boards top out around 50 dots, not hundreds — size was never
 * the thing that made a board hard.
 *
 * Every level here is asserted solvable by `pathfinderSolver` in
 * pathfinderLevels.test.ts, and asserted to land in its declared
 * difficulty tier by `pathfinderDifficulty.test.ts`'s calibration check —
 * those assertions are what make this content trustworthy, not the act of
 * generating or typing it.
 */

import type { DotPuzzle, Difficulty, GridPosition } from './pathfinderTypes'

function rectangle(rows: number, columns: number): GridPosition[] {
  const dots: GridPosition[] = []
  for (let row = 0; row < rows; row++) {
    for (let col = 0; col < columns; col++) dots.push({ row, col })
  }
  return dots
}

function withoutCells(dots: GridPosition[], removed: GridPosition[]): GridPosition[] {
  const removedKeys = new Set(removed.map((p) => `${p.row},${p.col}`))
  return dots.filter((p) => !removedKeys.has(`${p.row},${p.col}`))
}

/** Builds dots from one contiguous column range [fromCol, toCol] per row. */
function fromRowRanges(ranges: [fromCol: number, toCol: number][]): GridPosition[] {
  const dots: GridPosition[] = []
  ranges.forEach(([fromCol, toCol], row) => {
    for (let col = fromCol; col <= toCol; col++) dots.push({ row, col })
  })
  return dots
}

function block(rowFrom: number, rowTo: number, colFrom: number, colTo: number): GridPosition[] {
  const cells: GridPosition[] = []
  for (let row = rowFrom; row <= rowTo; row++) {
    for (let col = colFrom; col <= colTo; col++) cells.push({ row, col })
  }
  return cells
}

const EASY_LEVELS: DotPuzzle[] = [
  {
    id: 'easy-staggered-diamond',
    name: 'Staggered Diamond',
    difficulty: 'easy',
    rows: 5,
    columns: 5,
    // Row lengths 3, 5, 5, 4, 3. Row 0 is offset to columns 0-2 rather than
    // centered under row 1: a grid graph is bipartite by (row+col) parity,
    // and a Hamiltonian path over an even number of dots needs an exact
    // 10/10 color split — centering every odd-length row the same way skews
    // that split and makes the board provably unsolvable regardless of how
    // the path is drawn.
    dots: fromRowRanges([
      [0, 2],
      [0, 4],
      [0, 4],
      [0, 3],
      [1, 3],
    ]),
  },
  {
    id: 'easy-notched-corridor',
    name: 'Notched Corridor',
    difficulty: 'easy',
    rows: 5,
    columns: 5,
    dots: withoutCells(rectangle(5, 5), [
      { row: 1, col: 3 },
      { row: 2, col: 1 },
      { row: 3, col: 3 },
    ]),
  },
  {
    id: 'easy-cross-frame',
    name: 'Cross Frame',
    difficulty: 'easy',
    rows: 6,
    columns: 6,
    // A 6x6 square with each 2x2 corner cut off — a thick plus/cross shape.
    dots: withoutCells(rectangle(6, 6), [
      ...block(0, 1, 0, 1),
      ...block(0, 1, 4, 5),
      ...block(4, 5, 0, 1),
      ...block(4, 5, 4, 5),
    ]),
  },
  {
    id: 'easy-scattered-frame',
    name: 'Scattered Frame',
    difficulty: 'easy',
    rows: 5,
    columns: 6,
    // A single interior notch rather than scattered single-cell holes near
    // the edges — scattered edge-adjacent holes kept accidentally cutting a
    // corner or edge dot down to one remaining neighbor ("a leaf"), and a
    // path only has two ends, so more than two leaf dots makes a board
    // provably unsolvable no matter how it's drawn.
    dots: withoutCells(rectangle(5, 6), block(1, 2, 2, 3)),
  },
  {
    id: 'easy-notched-tall',
    name: 'Notched Tall',
    difficulty: 'easy',
    rows: 6,
    columns: 4,
    dots: withoutCells(rectangle(6, 4), [
      { row: 1, col: 1 },
      { row: 2, col: 3 },
      { row: 3, col: 0 },
      { row: 4, col: 2 },
    ]),
  },
]

const MEDIUM_LEVELS: DotPuzzle[] = [
  {
    id: 'medium-pocket-maze',
    name: 'Pocket Maze',
    difficulty: 'medium',
    rows: 4,
    columns: 4,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 3, col: 0 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
    ],
  },
  {
    id: 'medium-tight-corner',
    name: 'Tight Corner',
    difficulty: 'medium',
    rows: 4,
    columns: 4,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
      { row: 1, col: 0 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 3, col: 1 },
      { row: 3, col: 3 },
    ],
  },
  {
    id: 'medium-narrow-weave',
    name: 'Narrow Weave',
    difficulty: 'medium',
    rows: 5,
    columns: 4,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 3, col: 0 },
      { row: 3, col: 1 },
      { row: 3, col: 3 },
      { row: 4, col: 3 },
    ],
  },
  {
    id: 'medium-knotted-square',
    name: 'Knotted Square',
    difficulty: 'medium',
    rows: 5,
    columns: 4,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 3 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
      { row: 4, col: 0 },
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
    ],
  },
  {
    id: 'medium-small-snare',
    name: 'Small Snare',
    difficulty: 'medium',
    rows: 4,
    columns: 4,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 3, col: 0 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
    ],
  },
]

const HARD_LEVELS: DotPuzzle[] = [
  {
    id: 'hard-twisted-grid',
    name: 'Twisted Grid',
    difficulty: 'hard',
    rows: 5,
    columns: 5,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
      { row: 0, col: 4 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
      { row: 4, col: 0 },
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
    ],
  },
  {
    id: 'hard-dead-end-alley',
    name: 'Dead End Alley',
    difficulty: 'hard',
    rows: 5,
    columns: 5,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 4, col: 1 },
      { row: 4, col: 4 },
    ],
  },
  {
    id: 'hard-the-labyrinth',
    name: 'The Labyrinth',
    difficulty: 'hard',
    rows: 5,
    columns: 6,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
      { row: 0, col: 4 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 1, col: 5 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 2, col: 5 },
      { row: 3, col: 0 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 4, col: 0 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
    ],
  },
  {
    id: 'hard-backtrack-trap',
    name: 'Backtrack Trap',
    difficulty: 'hard',
    rows: 6,
    columns: 5,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 3 },
      { row: 0, col: 4 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
      { row: 5, col: 1 },
      { row: 5, col: 2 },
      { row: 5, col: 4 },
    ],
  },
  {
    id: 'hard-winding-trap',
    name: 'Winding Trap',
    difficulty: 'hard',
    rows: 6,
    columns: 6,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 4 },
      { row: 0, col: 5 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 1, col: 5 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 5 },
      { row: 3, col: 0 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 3, col: 5 },
      { row: 4, col: 0 },
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
      { row: 4, col: 5 },
      { row: 5, col: 0 },
      { row: 5, col: 3 },
      { row: 5, col: 4 },
      { row: 5, col: 5 },
    ],
  },
  {
    id: 'hard-puzzle-knot',
    name: 'Puzzle Knot',
    difficulty: 'hard',
    rows: 6,
    columns: 6,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
      { row: 0, col: 4 },
      { row: 0, col: 5 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 1, col: 5 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 2, col: 5 },
      { row: 3, col: 0 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 4, col: 0 },
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
      { row: 5, col: 0 },
      { row: 5, col: 1 },
      { row: 5, col: 3 },
      { row: 5, col: 4 },
    ],
  },
  {
    id: 'hard-tangled-weave',
    name: 'Tangled Weave',
    difficulty: 'hard',
    rows: 6,
    columns: 7,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
      { row: 0, col: 6 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 3 },
      { row: 1, col: 6 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 2, col: 5 },
      { row: 2, col: 6 },
      { row: 3, col: 0 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 4, col: 0 },
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
      { row: 4, col: 5 },
      { row: 4, col: 6 },
      { row: 5, col: 0 },
      { row: 5, col: 1 },
      { row: 5, col: 2 },
      { row: 5, col: 5 },
      { row: 5, col: 6 },
    ],
  },
  {
    id: 'hard-the-maze-box',
    name: 'The Maze Box',
    difficulty: 'hard',
    rows: 7,
    columns: 6,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 4 },
      { row: 0, col: 5 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 1, col: 5 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 2, col: 5 },
      { row: 3, col: 0 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 4, col: 0 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
      { row: 4, col: 5 },
      { row: 5, col: 0 },
      { row: 5, col: 3 },
      { row: 5, col: 4 },
      { row: 5, col: 5 },
      { row: 6, col: 0 },
      { row: 6, col: 2 },
      { row: 6, col: 3 },
    ],
  },
  {
    id: 'hard-dense-trap',
    name: 'Dense Trap',
    difficulty: 'hard',
    rows: 7,
    columns: 7,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
      { row: 0, col: 4 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 1, col: 5 },
      { row: 1, col: 6 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 2, col: 5 },
      { row: 2, col: 6 },
      { row: 3, col: 0 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
      { row: 5, col: 1 },
      { row: 5, col: 2 },
      { row: 5, col: 3 },
      { row: 5, col: 4 },
      { row: 5, col: 5 },
      { row: 5, col: 6 },
      { row: 6, col: 4 },
      { row: 6, col: 5 },
      { row: 6, col: 6 },
    ],
  },
  {
    id: 'hard-winding-corridor',
    name: 'Winding Corridor',
    difficulty: 'hard',
    rows: 6,
    columns: 7,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
      { row: 0, col: 4 },
      { row: 0, col: 5 },
      { row: 0, col: 6 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 1, col: 5 },
      { row: 1, col: 6 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 2, col: 5 },
      { row: 2, col: 6 },
      { row: 3, col: 0 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 4, col: 0 },
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 4, col: 4 },
      { row: 4, col: 6 },
      { row: 5, col: 0 },
      { row: 5, col: 1 },
      { row: 5, col: 2 },
      { row: 5, col: 4 },
      { row: 5, col: 5 },
      { row: 5, col: 6 },
    ],
  },
]

const LEGENDARY_LEVELS: DotPuzzle[] = [
  {
    id: 'legendary-the-gauntlet',
    name: 'The Gauntlet',
    difficulty: 'legendary',
    rows: 6,
    columns: 6,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 3 },
      { row: 0, col: 4 },
      { row: 0, col: 5 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 1, col: 5 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 2, col: 5 },
      { row: 3, col: 0 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 4, col: 0 },
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
      { row: 4, col: 5 },
      { row: 5, col: 1 },
      { row: 5, col: 2 },
      { row: 5, col: 3 },
      { row: 5, col: 4 },
      { row: 5, col: 5 },
    ],
  },
  {
    id: 'legendary-impossible-weave',
    name: 'Impossible Weave',
    difficulty: 'legendary',
    rows: 7,
    columns: 6,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 3 },
      { row: 0, col: 4 },
      { row: 0, col: 5 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 1, col: 5 },
      { row: 2, col: 0 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 3, col: 0 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 4, col: 0 },
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
      { row: 4, col: 5 },
      { row: 5, col: 0 },
      { row: 5, col: 1 },
      { row: 5, col: 2 },
      { row: 5, col: 3 },
      { row: 5, col: 4 },
      { row: 5, col: 5 },
      { row: 6, col: 0 },
      { row: 6, col: 1 },
      { row: 6, col: 2 },
      { row: 6, col: 3 },
      { row: 6, col: 4 },
      { row: 6, col: 5 },
    ],
  },
  {
    id: 'legendary-the-final-trap',
    name: 'The Final Trap',
    difficulty: 'legendary',
    rows: 7,
    columns: 8,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 0 },
      { row: 0, col: 1 },
      { row: 0, col: 3 },
      { row: 0, col: 4 },
      { row: 0, col: 6 },
      { row: 0, col: 7 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 1, col: 5 },
      { row: 1, col: 6 },
      { row: 1, col: 7 },
      { row: 2, col: 0 },
      { row: 2, col: 2 },
      { row: 2, col: 4 },
      { row: 2, col: 5 },
      { row: 2, col: 6 },
      { row: 2, col: 7 },
      { row: 3, col: 0 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 3, col: 7 },
      { row: 4, col: 0 },
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
      { row: 4, col: 5 },
      { row: 4, col: 6 },
      { row: 4, col: 7 },
      { row: 5, col: 1 },
      { row: 5, col: 2 },
      { row: 5, col: 3 },
      { row: 5, col: 4 },
      { row: 5, col: 5 },
      { row: 5, col: 6 },
      { row: 5, col: 7 },
      { row: 6, col: 1 },
      { row: 6, col: 2 },
      { row: 6, col: 3 },
      { row: 6, col: 4 },
      { row: 6, col: 5 },
      { row: 6, col: 6 },
      { row: 6, col: 7 },
    ],
  },
  {
    id: 'legendary-masters-snare',
    name: 'Master\'s Snare',
    difficulty: 'legendary',
    rows: 8,
    columns: 7,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 4 },
      { row: 0, col: 5 },
      { row: 0, col: 6 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 1, col: 5 },
      { row: 1, col: 6 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 2, col: 5 },
      { row: 2, col: 6 },
      { row: 3, col: 0 },
      { row: 3, col: 1 },
      { row: 3, col: 2 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 4, col: 0 },
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
      { row: 4, col: 4 },
      { row: 4, col: 5 },
      { row: 4, col: 6 },
      { row: 5, col: 0 },
      { row: 5, col: 1 },
      { row: 5, col: 2 },
      { row: 5, col: 3 },
      { row: 5, col: 4 },
      { row: 5, col: 5 },
      { row: 5, col: 6 },
      { row: 6, col: 0 },
      { row: 6, col: 1 },
      { row: 6, col: 2 },
      { row: 6, col: 3 },
      { row: 6, col: 4 },
      { row: 6, col: 5 },
      { row: 6, col: 6 },
      { row: 7, col: 0 },
      { row: 7, col: 2 },
      { row: 7, col: 3 },
      { row: 7, col: 4 },
      { row: 7, col: 5 },
      { row: 7, col: 6 },
    ],
  },
  {
    id: 'legendary-crooked-path',
    name: 'Crooked Path',
    difficulty: 'legendary',
    rows: 8,
    columns: 7,
    // Procedurally generated by pathfinderGenerator.ts (simulated annealing
    // over dot placement, using assessDifficulty's score as fitness) rather
    // than hand-authored.
    dots: [
      { row: 0, col: 1 },
      { row: 0, col: 2 },
      { row: 0, col: 4 },
      { row: 0, col: 5 },
      { row: 0, col: 6 },
      { row: 1, col: 0 },
      { row: 1, col: 1 },
      { row: 1, col: 2 },
      { row: 1, col: 3 },
      { row: 1, col: 4 },
      { row: 1, col: 5 },
      { row: 1, col: 6 },
      { row: 2, col: 0 },
      { row: 2, col: 1 },
      { row: 2, col: 2 },
      { row: 2, col: 3 },
      { row: 2, col: 4 },
      { row: 2, col: 5 },
      { row: 3, col: 3 },
      { row: 3, col: 4 },
      { row: 3, col: 5 },
      { row: 3, col: 6 },
      { row: 4, col: 0 },
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
      { row: 4, col: 5 },
      { row: 4, col: 6 },
      { row: 5, col: 0 },
      { row: 5, col: 1 },
      { row: 5, col: 2 },
      { row: 5, col: 3 },
      { row: 5, col: 4 },
      { row: 5, col: 5 },
      { row: 5, col: 6 },
      { row: 6, col: 0 },
      { row: 6, col: 1 },
      { row: 6, col: 2 },
      { row: 6, col: 3 },
      { row: 6, col: 4 },
      { row: 6, col: 5 },
      { row: 6, col: 6 },
      { row: 7, col: 0 },
      { row: 7, col: 1 },
      { row: 7, col: 2 },
      { row: 7, col: 3 },
      { row: 7, col: 4 },
      { row: 7, col: 5 },
      { row: 7, col: 6 },
    ],
  },
]

export const LEVELS_BY_DIFFICULTY: Record<Difficulty, DotPuzzle[]> = {
  easy: EASY_LEVELS,
  medium: MEDIUM_LEVELS,
  hard: HARD_LEVELS,
  legendary: LEGENDARY_LEVELS,
}

/** Easy levels first, then Medium, then Hard, then Legendary — the fixed
 * order the level select screen displays and the unlock progression steps
 * through. Random picking (the old `pickLevel`) is gone: with only a
 * handful of levels per tier, drawing randomly repeated the same map far
 * too often; a sequential unlock chain fixes that and gives "some maps
 * need to be unlocked" a real mechanism. */
export const ALL_LEVELS: DotPuzzle[] = [...EASY_LEVELS, ...MEDIUM_LEVELS, ...HARD_LEVELS, ...LEGENDARY_LEVELS]
